### ISSUE TITLE
Cast issue when unpacking 0.11.11+ replays

### ISSUE THREAD

**Issue by SakuraIsayeki** [Nodsoft/WoWS-ReplaysUnpack#24]
As of 0.11.11, unpacking replays is met with the following exception:
```
 Error when calling method subscription with hash Avatar_onArenaStateReceived
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Razorvine.Pickle.Objects.ClassDict'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at Nodsoft.WowsReplaysUnpack.ExtendedData.ExtendedDataController`1.AddPlayerToReplay(ArrayList properties)
   at Nodsoft.WowsReplaysUnpack.ExtendedData.ExtendedDataController`1.OnArenaStateReceived(Dictionary`2 arguments)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Nodsoft.WowsReplaysUnpack.Core.Entities.Entity.CallClientMethodWithDictionary(BinaryReader reader, Single packetTime, Object subscriptionTarget, EntityMethodDefinition methodDefinition, String hash, MethodBase methodInfo, MethodSubscriptionAttribute attribute)
```

It is theorized that this issue was caused by the introduction of the "Prime Target" player feature (aka Cookies), which might have caused a change in the User data structure. However this repmains incertain in absence of API documentation from Wargaming.
Further investigation is needed to diagnose the issue.

**Comment by SakuraIsayeki** [comment]
Exception source is revealed to be with the `ExtendedDataController`, when registering players: https://github.com/Nodsoft/WoWS-ReplaysUnpack/blob/hotfix/24/Nodsoft.WowsReplaysUnpack.ExtendedData/ExtendedDataController.cs#L98
The loop breaks on ID 25: `PlayerMode`, trying to register a dictionary when string values are present.

**Comment by SakuraIsayeki** [comment]
Property at ID 23 reveals a boolean that I can only assume is the property associated to the Cookie flag. 
Proceeding with closed testing to determine if assertion is correct, and will commit a fix if it's the case.
